language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "dfnC0gf4+Q2z5mg9EFB/ognhYEKR506hUUG9i6lBfvtook4Cz2vcc46sCpJ3MuAHEHcvaE4j71aTqdRPyzY0keqT7hB4b0QvRkqU3/CUbNJKy/wUE1WNugXzd4kZaz0AFv1XXGb65+B8EQRUjQDoI2bPrytFqxEOrfilj5RTm7M="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
