language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "UgCpKaVVcYNBjX1DSaTUoHV1toQRInDwbTAIMGh1lsiHN2XDk4RGk3EXgCAla/Ul2ouO4EAyKCeyaWBJC7bD7PXv54r1uSFzaEOOoekx7CLePOAYAd329EFfvmD/BKYdMIaMximVr4dXl4w6PmmzQBUtKzdtTnCGwIb7KvhuRX4="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
