var tree = [["Eloquent",,"",
                [["Asplode","Eloquent\/Asplode.html","",
                [["Error","Eloquent\/Asplode\/Error.html","",
                [["AbstractErrorException","Eloquent\/Asplode\/Error\/AbstractErrorException.html"," < ErrorException",
                [        ]],["ErrorException","Eloquent\/Asplode\/Error\/ErrorException.html"," < AbstractErrorException",
                [        ]],["ErrorExceptionInterface","Eloquent\/Asplode\/Error\/ErrorExceptionInterface.html","",
                [        ]],["FatalErrorException","Eloquent\/Asplode\/Error\/FatalErrorException.html"," < AbstractErrorException",
                [        ]],["FatalErrorExceptionInterface","Eloquent\/Asplode\/Error\/FatalErrorExceptionInterface.html","",
                [        ]],["NonFatalErrorExceptionInterface","Eloquent\/Asplode\/Error\/NonFatalErrorExceptionInterface.html","",
                [        ]]        ]],["Exception","Eloquent\/Asplode\/Exception.html","",
                [["AlreadyInstalledException","Eloquent\/Asplode\/Exception\/AlreadyInstalledException.html"," < Exception",
                [        ]],["AsplodeExceptionInterface","Eloquent\/Asplode\/Exception\/AsplodeExceptionInterface.html","",
                [        ]],["ErrorHandlingConfigurationException","Eloquent\/Asplode\/Exception\/ErrorHandlingConfigurationException.html"," < Exception",
                [        ]],["NotInstalledException","Eloquent\/Asplode\/Exception\/NotInstalledException.html"," < Exception",
                [        ]]        ]],["HandlerStack","Eloquent\/Asplode\/HandlerStack.html","",
                [["AbstractHandlerStack","Eloquent\/Asplode\/HandlerStack\/AbstractHandlerStack.html","",
                [        ]],["ErrorHandlerStack","Eloquent\/Asplode\/HandlerStack\/ErrorHandlerStack.html"," < AbstractHandlerStack",
                [        ]],["ExceptionHandlerStack","Eloquent\/Asplode\/HandlerStack\/ExceptionHandlerStack.html"," < AbstractHandlerStack",
                [        ]],["HandlerStackInterface","Eloquent\/Asplode\/HandlerStack\/HandlerStackInterface.html","",
                [        ]]        ]],["Asplode","Eloquent\/Asplode\/Asplode.html","",
                [        ]],["ErrorHandler","Eloquent\/Asplode\/ErrorHandler.html","",
                [        ]],["ErrorHandlerInterface","Eloquent\/Asplode\/ErrorHandlerInterface.html","",
                [        ]],["FatalErrorHandler","Eloquent\/Asplode\/FatalErrorHandler.html","",
                [        ]],["FatalErrorHandlerInterface","Eloquent\/Asplode\/FatalErrorHandlerInterface.html","",
                [        ]]        ]]        ]]        ]

